set_property SRC_FILE_INFO {cfile:D:/Tasks/shema2/shema2.srcs/constrs_1/new/board.xdc rfile:../../../shema2.srcs/constrs_1/new/board.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports IN]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C7 [get_ports {n[1][2]}]
